---
- name: "Check for distribution config : {{ ansible_facts['distribution'] }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_facts['distribution'] }}.yml"
  register: python_distribution_config

- name: "Run tasks : {{ ansible_facts['distribution'] }}"
  ansible.builtin.include_tasks: "{{ ansible_facts['distribution'] }}.yml"
  when: python_distribution_config.stat.exists

- name: "Install uv"
  community.general.pipx:
    executable: pipx
    name: uv
